# Generated by Django 4.1.2 on 2022-10-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=20)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('Con_Password', models.CharField(max_length=20)),
            ],
        ),
    ]
